import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show compute;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image/image.dart' as img;
import 'package:share_plus/share_plus.dart';

import '../../../../core/utils/friendly_error.dart';
import '../../../../core/utils/toolkit_paths.dart';
import '../../../../models/toolkit_file.dart';
import '../../../../providers/app_providers.dart';
import '../../../../services/toolkit/scan_image_processing_service.dart';
import '../../../../services/toolkit/scanner_pdf_service.dart';
import 'toolkit_providers.dart';

/// Scanner (V2 Phase 5B) - a multi-page editable session, not a linear
/// pick->process->result pipeline like `ImageCompressUiState`/
/// `ImageResizeUiState` (Phase 5A). Deliberately one plain mutable state
/// class rather than a sealed hierarchy: the user adds/removes/reorders/
/// edits pages in any order, any number of times, before ever generating a
/// PDF - there's no single forward-only sequence of states to model,
/// closer in shape to `NotesController`'s CRUD-list state than to
/// `DocumentImportUiState`'s pipeline.
class ScannerState {
  const ScannerState({
    this.pages = const [],
    this.isBusy = false,
    this.error,
    this.generatedPdfBytes,
    this.savedFile,
    this.lastDeletedPage,
    this.lastDeletedIndex,
  });

  final List<ScannedPage> pages;

  /// True while capturing/importing/editing a page or generating/saving
  /// the PDF - the UI disables page actions and shows progress while this
  /// is true, rather than allowing overlapping operations on the same
  /// session.
  final bool isBusy;
  final String? error;

  /// Set once "Generate PDF" has run against the current [pages] - any
  /// page mutation after that clears it again, since the generated bytes
  /// no longer reflect the current page set.
  final Uint8List? generatedPdfBytes;
  final ToolkitFile? savedFile;

  /// One-shot undo state for the most recent page deletion - cleared by
  /// any other mutation, matching a simple "Undo" snackbar's usual
  /// lifetime (available immediately after the action it undoes, not
  /// indefinitely).
  final ScannedPage? lastDeletedPage;
  final int? lastDeletedIndex;

  bool get canUndoDelete => lastDeletedPage != null;

  ScannerState copyWith({
    List<ScannedPage>? pages,
    bool? isBusy,
    String? error,
    bool clearError = false,
    Uint8List? generatedPdfBytes,
    bool clearGeneratedPdf = false,
    ToolkitFile? savedFile,
    ScannedPage? lastDeletedPage,
    int? lastDeletedIndex,
    bool clearLastDeleted = false,
  }) {
    return ScannerState(
      pages: pages ?? this.pages,
      isBusy: isBusy ?? this.isBusy,
      error: clearError ? null : (error ?? this.error),
      generatedPdfBytes: clearGeneratedPdf ? null : (generatedPdfBytes ?? this.generatedPdfBytes),
      savedFile: savedFile ?? this.savedFile,
      lastDeletedPage: clearLastDeleted ? null : (lastDeletedPage ?? this.lastDeletedPage),
      lastDeletedIndex: clearLastDeleted ? null : (lastDeletedIndex ?? this.lastDeletedIndex),
    );
  }
}

class ScannerController extends Notifier<ScannerState> {
  int _idCounter = 0;

  @override
  ScannerState build() => const ScannerState();

  String _newPageId() => 'page_${DateTime.now().microsecondsSinceEpoch}_${_idCounter++}';

  Future<void> _addPage(Uint8List sourceBytes) async {
    state = state.copyWith(isBusy: true, clearError: true);
    try {
      final jpegBytes = await compute(_normalizeToJpegRequest, sourceBytes);
      final decoded = img.decodeJpg(jpegBytes);
      if (decoded == null) {
        throw const ScanImageProcessingException('That image could not be read.');
      }
      final page = ScannedPage(
        id: _newPageId(),
        jpegBytes: jpegBytes,
        width: decoded.width,
        height: decoded.height,
      );
      state = state.copyWith(
        pages: [...state.pages, page],
        isBusy: false,
        clearGeneratedPdf: true,
        clearLastDeleted: true,
      );
    } on ScanImageProcessingException catch (e) {
      state = state.copyWith(isBusy: false, error: e.message);
    } catch (_) {
      state = state.copyWith(
        isBusy: false,
        error: 'Could not add that page. Please try again.',
      );
    }
  }

  Future<void> captureFromCamera() async {
    try {
      final picked = await ref.read(toolkitImagePickerServiceProvider).captureFromCamera();
      if (picked == null) return;
      await _addPage(picked.bytes);
    } catch (e) {
      // Production Readiness audit: the picker itself can throw (camera/
      // gallery permission denied, or another app holding the camera) -
      // previously unguarded here, unlike `_addPage`'s own try/catch a few
      // lines below, which only covers processing an already-picked image.
      state = state.copyWith(error: friendlyErrorMessage(e));
    }
  }

  Future<void> importFromGallerySingle() async {
    try {
      final picked = await ref.read(toolkitImagePickerServiceProvider).pickFromGallery();
      if (picked == null) return;
      await _addPage(picked.bytes);
    } catch (e) {
      state = state.copyWith(error: friendlyErrorMessage(e));
    }
  }

  /// Imports every photo the user multi-selects in one gallery visit,
  /// appending them in the order the picker returned them - the common
  /// "I already photographed all the pages, now build the PDF" workflow.
  Future<void> importMultipleFromGallery() async {
    try {
      final picked = await ref.read(toolkitImagePickerServiceProvider).pickMultipleFromGallery();
      for (final image in picked) {
        await _addPage(image.bytes);
      }
    } catch (e) {
      state = state.copyWith(error: friendlyErrorMessage(e));
    }
  }

  void deletePage(String id) {
    final index = state.pages.indexWhere((p) => p.id == id);
    if (index == -1) return;
    final removed = state.pages[index];
    final updated = [...state.pages]..removeAt(index);
    state = state.copyWith(
      pages: updated,
      clearGeneratedPdf: true,
      lastDeletedPage: removed,
      lastDeletedIndex: index,
    );
  }

  void undoDeletePage() {
    final page = state.lastDeletedPage;
    final index = state.lastDeletedIndex;
    if (page == null || index == null) return;
    final updated = [...state.pages];
    updated.insert(index.clamp(0, updated.length), page);
    state = state.copyWith(pages: updated, clearGeneratedPdf: true, clearLastDeleted: true);
  }

  void reorderPage(int oldIndex, int newIndex) {
    if (oldIndex == newIndex) return;
    final updated = [...state.pages];
    final page = updated.removeAt(oldIndex);
    updated.insert(newIndex, page);
    state = state.copyWith(pages: updated, clearGeneratedPdf: true, clearLastDeleted: true);
  }

  Future<void> rotatePage(String id, ScanRotation rotation) async {
    final index = state.pages.indexWhere((p) => p.id == id);
    if (index == -1) return;
    state = state.copyWith(isBusy: true, clearError: true);
    try {
      final page = state.pages[index];
      final rotatedBytes = await compute(
        _RotatePageRequest.run,
        _RotatePageRequest(page.jpegBytes, rotation),
      );
      final decoded = img.decodeJpg(rotatedBytes)!;
      final updated = [...state.pages];
      updated[index] = ScannedPage(
        id: page.id,
        jpegBytes: rotatedBytes,
        width: decoded.width,
        height: decoded.height,
      );
      state = state.copyWith(pages: updated, isBusy: false, clearGeneratedPdf: true);
    } catch (_) {
      state = state.copyWith(isBusy: false, error: 'Could not rotate that page.');
    }
  }

  /// Applies a 4-corner perspective correction (or, when [quad] is exactly
  /// the page's own full-image rectangle, effectively a no-op crop) to one
  /// page, replacing its working image in place.
  Future<void> applyPerspectiveCorrection(String id, ScanQuad quad) async {
    final index = state.pages.indexWhere((p) => p.id == id);
    if (index == -1) return;
    state = state.copyWith(isBusy: true, clearError: true);
    try {
      final page = state.pages[index];
      final correctedBytes = await compute(
        runPerspectiveCorrection,
        PerspectiveCorrectionRequest(jpegBytes: page.jpegBytes, quad: quad),
      );
      final decoded = img.decodeJpg(correctedBytes)!;
      final updated = [...state.pages];
      updated[index] = ScannedPage(
        id: page.id,
        jpegBytes: correctedBytes,
        width: decoded.width,
        height: decoded.height,
      );
      state = state.copyWith(pages: updated, isBusy: false, clearGeneratedPdf: true);
    } on ScanImageProcessingException catch (e) {
      state = state.copyWith(isBusy: false, error: e.message);
    } catch (_) {
      state = state.copyWith(isBusy: false, error: 'Could not adjust that page. Please try again.');
    }
  }

  Future<void> generatePdf() async {
    if (state.pages.isEmpty) {
      state = state.copyWith(error: 'Add at least one page first.');
      return;
    }
    state = state.copyWith(isBusy: true, clearError: true);
    try {
      final bytes = await ref.read(scannerPdfServiceProvider).buildPdf(state.pages);
      state = state.copyWith(isBusy: false, generatedPdfBytes: bytes);
    } on ScannerPdfException catch (e) {
      state = state.copyWith(isBusy: false, error: e.message);
    } catch (_) {
      state = state.copyWith(
        isBusy: false,
        error: 'Could not generate the PDF. Please try again.',
      );
    }
  }

  Future<ToolkitFile?> save() async {
    final bytes = state.generatedPdfBytes;
    if (bytes == null) return null;
    if (state.savedFile != null) return state.savedFile;

    final outputPath = await newToolkitOutputPath(ToolkitToolType.scan, 'pdf');
    await File(outputPath).writeAsBytes(bytes);

    final now = DateTime.now();
    final saved = ToolkitFile(
      id: null,
      toolType: ToolkitToolType.scan,
      title: 'Scan ${_formatTimestamp(now)}',
      outputPath: outputPath,
      fileSizeBytes: bytes.lengthInBytes,
      originalFileSizeBytes: null,
      isFavorite: false,
      createdAt: now,
      updatedAt: now,
      pageCount: state.pages.length,
    );
    final id = await ref.read(toolkitFileRepositoryProvider).insert(saved);
    ref.invalidate(toolkitFileListProvider);

    final withId = ToolkitFile(
      id: id,
      toolType: saved.toolType,
      title: saved.title,
      outputPath: saved.outputPath,
      fileSizeBytes: saved.fileSizeBytes,
      originalFileSizeBytes: saved.originalFileSizeBytes,
      isFavorite: saved.isFavorite,
      createdAt: saved.createdAt,
      updatedAt: saved.updatedAt,
      pageCount: saved.pageCount,
    );
    state = state.copyWith(savedFile: withId);
    return withId;
  }

  Future<void> share() async {
    final bytes = state.generatedPdfBytes;
    if (bytes == null) return;
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile.fromData(bytes, name: 'scan.pdf', mimeType: 'application/pdf')],
      ),
    );
  }

  void reset() {
    state = const ScannerState();
  }

  String _formatTimestamp(DateTime t) {
    String two(int n) => n.toString().padLeft(2, '0');
    return '${t.year}-${two(t.month)}-${two(t.day)} ${two(t.hour)}${two(t.minute)}';
  }
}

Uint8List _normalizeToJpegRequest(Uint8List bytes) => normalizeScannedPageToJpeg(bytes);

class _RotatePageRequest {
  const _RotatePageRequest(this.jpegBytes, this.rotation);
  final Uint8List jpegBytes;
  final ScanRotation rotation;

  static Uint8List run(_RotatePageRequest request) =>
      rotateScannedPage(request.jpegBytes, request.rotation);
}

final scannerControllerProvider = NotifierProvider<ScannerController, ScannerState>(
  ScannerController.new,
);
